import express from 'express';
import cors from 'cors';
import swaggerUi from 'swagger-ui-express';
import fs from 'fs';
import path from 'path';

import { RegisterRoutes } from './generated/routes';
import { errorHandler } from './middlewares/errorHandler';

export function createApp() {
  const app = express();

  app.use(cors());
  app.use(express.json({ limit: '1mb' }));

  app.get('/health', (_req, res) => {
    res.json({ status: 'ok' });
  });

  // Swagger docs (generated by tsoa)
  const swaggerPathCandidates = [
    path.join(__dirname, 'generated/swagger.json'),
    path.join(process.cwd(), 'src/generated/swagger.json'),
    path.join(process.cwd(), 'dist/generated/swagger.json'),
  ];

  let swaggerDoc: any = null;
  for (const p of swaggerPathCandidates) {
    if (fs.existsSync(p)) {
      swaggerDoc = JSON.parse(fs.readFileSync(p, 'utf8'));
      break;
    }
  }

  if (swaggerDoc) {
    app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDoc));
  } else {
    console.warn('Swagger spec not found. Run: npm run tsoa:spec');
  }

  // Register TSOA routes
  RegisterRoutes(app);

  // 404 handler (after routes)
  app.use((_req, res) => {
    res.status(404).json({ message: 'Not Found' });
  });

  // Error handler must be last
  app.use(errorHandler);

  return app;
}
